### ISSUE TITLE
[BE] DB 구조 설계 및 세팅

### ISSUE THREAD

**Issue by blossun** [codesquad-member-2020/issue-tracker-09#6]
- DB ERD 설계
- DB 연결

**Comment by blossun** [comment]
xㅋㅇㅋ

**Comment by Limwin94** [comment]
ㄴㄴㄴ

**Comment by blossun** [comment]
![issue_tracker_ver01](https://user-images.githubusercontent.com/35985636/84245592-3d203900-ab40-11ea-9718-e2b32ae3a811.png)

**Comment by blossun** [comment]
milestone의 완료일 타입을 Datetime → Date 로 수정

**Comment by blossun** [comment]
milestone 완료일 필드명 completion_date → due_on으로 수정

**Comment by blossun** [comment]
- BLOB 데이터 타입 → TEXT로 변경
- issue의 is_open varchar → open BOOLEAN 으로 변경
![issue_tracker_ver02](https://user-images.githubusercontent.com/35985636/84737014-059f0a00-afe2-11ea-83ef-04ab7f31aa52.png)

**Comment by blossun** [comment]
- issue 테이블 contents 데이터 타입 TEXT로 변경
- comment에 작성자 필드 writer 추가
![issue_tracker_ver03](https://user-images.githubusercontent.com/35985636/84775521-4b77c480-b01a-11ea-83cb-3ff3db2571ca.png)
